### ISSUE TITLE
Document creating a service on uberspace

### ISSUE THREAD

**Issue by besendorf** [EggiJan/uberspace-webhook-server#2]
As this is a tool intended for uberspace it would be nice to document how to use this as a service.
https://manual.uberspace.de/daemons-supervisord/

**Comment by EggiJan** [comment]
Hey, thanks for adding this issue!
Since the usage of this webhook-server is not limited to using it on Uberspace, I will just link to their documentation in the README.
Feel free to open a PR with more detailed instructions :)
